### ISSUE TITLE
Rhino 7 1. Solution exception:Cloth: Group index 0 already in use!

### ISSUE THREAD

**Issue by SpaceArchitecture** [HeinzBenjamin/FlexCLI#12]
Hello there, old repo but still a col project, impossible to add two cloths or more to a scene, even while changing the groups index.
Maybe it's Rhino 7 but here's the message : 1. Solution exception:Cloth: Group index 0 already in use!
![image](https://user-images.githubusercontent.com/43206650/185537003-03b52a5b-1951-4f0d-80e8-344cd973c57c.png)

**Comment by AlexPrada14** [comment]
This happens because in the last modification of the software they made the group index zero by default and even if you try to change it, you cannot

**Comment by SpaceArchitecture** [comment]
That's a huge bummer, only one piece of cloth forever in Rhino then

**Comment by HeinzBenjamin** [comment]
Hi there,

unfortunately I don't have time to maintain this project at the moment. Feel free to pull the source code and build upon what I did.

Cheers 
Ben

**Comment by AlexPrada14** [comment]
Hello Benjamin,

Thank you for this project that is a great contribution. Indeed I am currently learning how to work on what you did with the objective of modifying some things and see if they work. One of the applications that I'm trying to run consists of a cloth which is filled with a fluid that emerges from a fountain object, however I can't get the cloth and fluid particles to interact. Do you know if this is possible with what you have developed so far and I am missing something or do I actually have to modify the code? because according to the NvFlex videos it is possible but in your videos you don't have any similar concrete example. Thanks in advance.

Greetings
Alex

**Comment by SpaceArchitecture** [comment]
There should be a new thread, what you mention is another issue

**Comment by AlexPrada14** [comment]
Yes, you're right
